<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\bam.encryption\bam.encryption\bam.encryption.csproj" />
      <ProjectReference Include="..\bam.storage\bam.storage.csproj" />
    </ItemGroup>

</Project>
