
using Bam.Encryption;

namespace Bam.Storage.Encryption;

public class OpaqueKeyValueStorage : IKeyValueStorage
{
    
    // TODO: define an encrypted storage to hold hmac keys generated by
    // the hmac provider.
    public OpaqueKeyValueStorage(IHmacKeyProvider hmacKeyProvider)
    {
        this.HmacKeyProvider = hmacKeyProvider;
    }

    protected IHmacKeyProvider HmacKeyProvider
    {
        get;
        set;
    }
    
    protected IKeyValue Transform(IKeyValue keyValue)
    {
       throw new NotImplementedException();
    }
    
    public IKeyValueSaveResult Save(IKeyValue keyValue)
    {
        throw new NotImplementedException();
    }

    public IKeyValue Get(string key)
    {
        throw new NotImplementedException();
    }
}